---
name: Publish App

on:
  push:
    tags:
      - 'app/v*.*.*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Set app version
        id: set_version
        shell: bash
        run: printf 'app_version=%s\n' "${GITHUB_REF_NAME#app/v}" >> "$GITHUB_OUTPUT"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements-ci-app.txt
            requirements.txt

      - name: Install dependencies
        run: pip install -r requirements-ci-app.txt

      - name: Build
        run: pyinstaller --noconsole --name byzantine-chant-ocr app.py
        working-directory: src

      - name: Archive
        shell: pwsh
        run: |
          cd src/dist
          if ($env:RUNNER_OS -eq "Windows") {
            7z a byzantine-chant-ocr-${{ steps.set_version.outputs.app_version }}-${{ runner.os }}.zip byzantine-chant-ocr 
          }
          elseif ($env:RUNNER_OS -eq "macOS") {
            zip -r byzantine-chant-ocr-${{ steps.set_version.outputs.app_version }}-${{ runner.os }}.zip byzantine-chant-ocr.app 
          }
          else {
            zip -r byzantine-chant-ocr-${{ steps.set_version.outputs.app_version }}-${{ runner.os }}.zip byzantine-chant-ocr
          }

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: src/dist/byzantine-chant-ocr-${{ steps.set_version.outputs.app_version }}-${{ runner.os }}.zip
          draft: true
